### Registro de usuario
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "test",
    "password": "123"
}

### Login de usuario
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "test",
    "password": "123"
}

### Obtener todos los productos (protegido)
GET http://localhost:3000/products

### Obtener un producto por ID (protegido)
GET http://localhost:3000/products/11

### logout de usuario
GET http://localhost:3000/logout

### Agregar un nuevo producto (protegido)
POST http://localhost:3000/products/
Content-Type: application/json

{
      "id": 10,
      "codigo": 83635,
      "nombre": "Cepillo de dientes",
      "precio": 4.99,
      "categoria": "Higiene personal"
}

### Editar un producto por ID (protegido)
PATCH http://localhost:3000/products/3
Content-Type: application/json

{
      "id": 10,
      "codigo": 8335,
      "nombre": "Cepillo de dientes",
      "precio": 5.99,
      "categoria": "Higiene personal"
}

### Eliminar un producto por ID (protegido)
DELETE http://localhost:3000/products/10